name: Bug
description: Report a bug or other issue

body:
    -   type: input
        id: package-version
        attributes:
            label: Package Wizard Version
            description: Provide **Package Wizard** version in X.Y.Z format (run `package --version` to get it)
        validations:
            required: true

    -   type: input
        id: php-version
        attributes:
            label: PHP Version
            description: Which PHP version `Package Wizard` is run on?
        validations:
            required: true

    -   type: textarea
        id: description
        attributes:
            label: Description
            description: |
                Be as specific and detailed as possible to help us triaging your issue. Screenshots and/or animations can be very useful in helping to understand the issue you're facing.

                Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
                Tip: You can use https://www.screentogif.com to record animations and videos.
        validations:
            required: true

    -   type: textarea
        id: steps
        attributes:
            label: Steps to reproduce
            description: Take some time to try and reproduce the issue, then explain how to do so here.
        validations:
            required: true

    -   type: textarea
        id: error
        attributes:
            label: Error
            description: Copy the text from the console that displays the error into this field.
        validations:
            required: false

    -   type: checkboxes
        id: terms
        attributes:
            label: Contribution Checks
            options:
                -   label: I have verified if this problem was already reported
                    required: true
                -   label: I am familiar with ["Feature or bug?"](https://package-wizard.com/feature-or-bug.html)
                    required: true

    -   type: markdown
        attributes:
            value: |
                ❤️ The Dragon Code? Please consider supporting our collective on [Boosty](https://boosty.to/dragon-code).
