name: Feature Proposal
description: Propose a new feature

body:
    -   type: markdown
        attributes:
            value: |
                Thanks for taking the time to fill out this bug report!

                ⚠️Review existing issues to see whether someone else has already reported your issue.

    -   type: textarea
        id: description
        attributes:
            label: Feature description
            description: |
                Think through your proposal and describe it clearly.

                Note that features are only added to the most recent version of **Package Wizard**.
        validations:
            required: true

    -   type: markdown
        attributes:
            value: |
                ❤️ The Dragon Code? Please consider supporting our collective on [Boosty](https://boosty.to/dragon-code).
