name: Publish the released PHAR

on:
    release:
        types: [ created ]
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag release version'
                required: true

jobs:
    publish:
        runs-on: ubuntu-latest

        name: Release PHAR

        steps:
            -   name: Extract the tag version
                id: tag
                run: |
                    if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                      GITHUB_REF=${{ github.event.inputs.tag }}
                    fi          
                    echo "tag=${GITHUB_REF##*v}" >> "$GITHUB_OUTPUT"
            -   name: Checkout the code
                uses: actions/checkout@v4
                with:
                    submodules: true
                    ref: v${{ steps.tag.outputs.tag }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    ini-values: error_reporting=E_ALL
                    coverage: none

            -   name: Upload the PHAR artifact
                uses: actions/upload-artifact@v4
                with:
                    name: paw.phar
                    path: builds/paw

            -   name: Rename file
                run: mv builds/paw builds/paw.phar

            -   name: Upload the PHAR to release
                run: gh release upload ${{ steps.tag.outputs.tag }} builds/paw.phar
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
