name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    draft:
        name: Draft
        uses: TheDragonCode/.github/.github/workflows/release-drafter.yml@main

    build:
        runs-on: ubuntu-latest

        name: Buils Application

        needs: draft

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Generate docs trigger
                uses: myrotvorets/trigger-repository-dispatch-action@v2.0.2
                with:
                    token: ${{ secrets.COMPOSER_TOKEN }}
                    repo: package-wizard/installer
                    type: build
                    payload: '{"tag": "${{ needs.draft.outputs.tag_name }}"}'
