name: Tests

on:
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        -   cron: '15 2 * * *'

permissions: read-all

jobs:
    unit:
        runs-on: ${{ matrix.os }}-latest

        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu, windows ]
                php: [ 8.2, 8.3, 8.4 ]

        name: OS ${{ matrix.os }} - PHP ${{ matrix.php }}

        steps:
            -   name: Set git to use LF
                if: ${{ matrix.os == 'windows' }}
                run: |
                    git config --global core.autocrlf false
                    git config --global core.eol lf

            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, fileinfo
                    ini-values: error_reporting=E_ALL, memory_limit=512M
                    coverage: none

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

            -   name: Execute tests
                run: composer test
