name: Tests

on:
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        -   cron: '15 2 * * *'

permissions: read-all

jobs:
    types:
        runs-on: ubuntu-latest

        name: Types

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    coverage: none

            -   name: Install dependencies
                run: composer install --no-progress --no-scripts --optimize-autoloader --no-interaction --ansi

            -   name: Types tests
                run: composer test:types

    coverage:
        runs-on: ubuntu-latest

        name: Coverage

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    coverage: xdebug

            -   name: Install dependencies
                run: composer install --no-progress --no-scripts --optimize-autoloader --no-interaction --ansi

            -   name: Types tests
                run: composer test:coverage

    misspelling:
        runs-on: ubuntu-latest

        name: Misspelling

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    coverage: none

            -   name: Install Aspell
                run: sudo apt-get install aspell aspell-en

            -   name: Install dependencies
                run: composer install --no-progress --no-scripts --optimize-autoloader --no-interaction --ansi

            -   name: Misspelling tests
                run: composer test:misspelling

    unit:
        runs-on: ${{ matrix.os }}-latest

        strategy:
            fail-fast: true
            matrix:
                os: [ ubuntu, windows ]
                php: [ 8.2, 8.3, 8.4 ]

        name: ${{ matrix.os }} - php ${{ matrix.php }}

        steps:
            -   name: Set git to use LF
                if: ${{ matrix.os == 'windows' }}
                run: |
                    git config --global core.autocrlf false
                    git config --global core.eol lf

            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    coverage: none

            -   uses: actions/setup-node@v4
                with:
                    node-version: 22

            -   name: Prepare Yarn
                run: |
                    npm install -g corepack
                    yarn set version stable

            -   name: Remove Peck
                run: composer remove peckphp/peck --dev --no-progress --no-scripts --no-install --ignore-platform-reqs --no-interaction --ansi

            -   name: Install dependencies
                run: composer install --no-progress --no-scripts --optimize-autoloader --no-interaction --ansi

            -   name: Unit tests
                run: composer test:unit
