name: Tests

on:
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        -   cron: '15 2 * * *'

permissions: read-all

jobs:
    types:
        runs-on: ubuntu-latest

        name: Types

        steps:
            -   name: Checkout code
                uses: actions/checkout@v5

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    coverage: none

            -   name: Install dependencies
                run: composer install --no-progress --no-scripts --optimize-autoloader --no-interaction --ansi

            -   name: Types tests
                run: composer test:types

    coverage:
        runs-on: ubuntu-latest

        name: Coverage

        steps:
            -   name: Checkout code
                uses: actions/checkout@v5

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    coverage: xdebug

            -   name: Install dependencies
                run: composer install --no-progress --no-scripts --optimize-autoloader --no-interaction --ansi

            -   name: Types tests
                run: composer test:coverage

    linux:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ 8.2, 8.3, 8.4 ]

        name: Ubuntu - PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v5

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    coverage: none

            -   uses: actions/setup-node@v5
                with:
                    node-version: 22

            -   name: Prepare Yarn
                run: sudo corepack enable

            -   name: Install dependencies
                run: composer install --no-progress --no-scripts --optimize-autoloader --no-interaction --ansi

            -   name: Unit tests
                run: sudo vendor/bin/pest --parallel

    windows:
        runs-on: windows-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ 8.2, 8.3, 8.4 ]

        name: Windows - PHP ${{ matrix.php }}

        steps:
            -   name: Set git to use LF
                run: |
                    git config --global core.autocrlf false
                    git config --global core.eol lf

            -   name: Checkout code
                uses: actions/checkout@v5

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, iconv, json, dom, fileinfo, tokenizer
                    coverage: none

            -   uses: actions/setup-node@v5
                with:
                    node-version: 22

            -   name: Install dependencies
                run: composer install --no-progress --no-scripts --optimize-autoloader --no-interaction --ansi

            -   name: Unit tests
                run: composer test:unit
